server:
  port: 8080

spring:
  application:
    name: rootdocs
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 900000
  refresh-expiration: 604800000

seed:
  admin-password: ${SEED_ADMIN_PASSWORD}
  leitor-password: ${SEED_LEITOR_PASSWORD}